### ISSUE TITLE
Error in dockerhub tag

### ISSUE THREAD

**Issue by migel** [estesp/manifest-tool#141]
The image `mplatform/manifest-tool:v1.0.3-linux-arm64` on dockerhub is for `linux/amd64` platform

https://hub.docker.com/layers/mplatform/manifest-tool/v1.0.3-linux-arm64/images/sha256-4293deb209ae304d08dc538f7447fe6997c436d9a92857cc16732df17eb6e4e7?context=explore

<img width="585" alt="image" src="https://user-images.githubusercontent.com/3897227/148701672-f966ca9c-6121-467b-abda-d88264389715.png">

**Comment by estesp** [comment]
This has been corrected with the v2.0.0 release that went out today. `docker buildx` with the `--platform` flag is now being used so that images have the correct platform notation, even though the older v1.x images had the "right" binary inside them, the way they were built was a bit of a hack and showed the host/build platform instead of the target for the image itself.

Please let me know if you are able to find any issues with the v2.0.0 tags; I believe you should find that they are all a correct match between the binary inside as well as the image platform OS/arch contents.
